version: '3'
services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
#    networks:
#      - fitness-center
#
#networks:
#  fitness-center:
#    driver: bridge