/**
 * Fitness center backend API
 * backend API for Fitness center
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The AddTrainerRequest model module.
 * @module model/AddTrainerRequest
 * @version 1.0.0
 */
class AddTrainerRequest {
    /**
     * Constructs a new <code>AddTrainerRequest</code>.
     * @alias module:model/AddTrainerRequest
     */
    constructor() {

        AddTrainerRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {
    }

    /**
     * Constructs a <code>AddTrainerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddTrainerRequest} obj Optional instance to populate.
     * @return {module:model/AddTrainerRequest} The populated <code>AddTrainerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddTrainerRequest();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddTrainerRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddTrainerRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}


/**
 * @member {Number} userId
 */
AddTrainerRequest.prototype['userId'] = undefined;


export default AddTrainerRequest;

