/**
 * Fitness center backend API
 * backend API for Fitness center
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FitnessCenterBackendApi);
  }
}(this, function(expect, FitnessCenterBackendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FitnessCenterBackendApi.GroupClass();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GroupClass', function() {
    it('should create an instance of GroupClass', function() {
      // uncomment below and update the code to test GroupClass
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be.a(FitnessCenterBackendApi.GroupClass);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be();
    });

    it('should have the property timeFrom (base name: "timeFrom")', function() {
      // uncomment below and update the code to test the property timeFrom
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be();
    });

    it('should have the property timeTo (base name: "timeTo")', function() {
      // uncomment below and update the code to test the property timeTo
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be();
    });

    it('should have the property capacity (base name: "capacity")', function() {
      // uncomment below and update the code to test the property capacity
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be();
    });

    it('should have the property room (base name: "room")', function() {
      // uncomment below and update the code to test the property room
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be();
    });

    it('should have the property sportType (base name: "sportType")', function() {
      // uncomment below and update the code to test the property sportType
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be();
    });

    it('should have the property trainers (base name: "trainers")', function() {
      // uncomment below and update the code to test the property trainers
      //var instance = new FitnessCenterBackendApi.GroupClass();
      //expect(instance).to.be();
    });

  });

}));
