/**
 * Fitness center backend API
 * backend API for Fitness center
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddTrainerRequest from './model/AddTrainerRequest';
import GroupClass from './model/GroupClass';
import GroupClassTrainersInner from './model/GroupClassTrainersInner';
import Room from './model/Room';
import SportType from './model/SportType';
import User from './model/User';
import GroupClassApi from './api/GroupClassApi';
import RoomApi from './api/RoomApi';
import SportTypeApi from './api/SportTypeApi';
import UserApi from './api/UserApi';


/**
 * backend API for Fitness center.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var FitnessCenterBackendApi = require('index'); // See note below*.
 * var xxxSvc = new FitnessCenterBackendApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new FitnessCenterBackendApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new FitnessCenterBackendApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new FitnessCenterBackendApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 1.0.0
 */
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
        ApiClient,

    /**
     * The AddTrainerRequest model constructor.
     * @property {module:model/AddTrainerRequest}
     */
        AddTrainerRequest,

    /**
     * The GroupClass model constructor.
     * @property {module:model/GroupClass}
     */
        GroupClass,

    /**
     * The GroupClassTrainersInner model constructor.
     * @property {module:model/GroupClassTrainersInner}
     */
        GroupClassTrainersInner,

    /**
     * The Room model constructor.
     * @property {module:model/Room}
     */
        Room,

    /**
     * The SportType model constructor.
     * @property {module:model/SportType}
     */
        SportType,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
        User,

    /**
     * The GroupClassApi service constructor.
     * @property {module:api/GroupClassApi}
     */
        GroupClassApi,

    /**
     * The RoomApi service constructor.
     * @property {module:api/RoomApi}
     */
        RoomApi,

    /**
     * The SportTypeApi service constructor.
     * @property {module:api/SportTypeApi}
     */
        SportTypeApi,

    /**
     * The UserApi service constructor.
     * @property {module:api/UserApi}
     */
        UserApi
};
