/**
 * Fitness center backend API
 * backend API for Fitness center
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FitnessCenterBackendApi);
  }
}(this, function(expect, FitnessCenterBackendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FitnessCenterBackendApi.GroupClassApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GroupClassApi', function() {
    describe('addTrainer', function() {
      it('should call addTrainer successfully', function(done) {
        //uncomment below and update the code to test addTrainer
        //instance.addTrainer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteGroupClass', function() {
      it('should call deleteGroupClass successfully', function(done) {
        //uncomment below and update the code to test deleteGroupClass
        //instance.deleteGroupClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGroupClass', function() {
      it('should call getGroupClass successfully', function(done) {
        //uncomment below and update the code to test getGroupClass
        //instance.getGroupClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGroupClasses', function() {
      it('should call getGroupClasses successfully', function(done) {
        //uncomment below and update the code to test getGroupClasses
        //instance.getGroupClasses(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putGroupClass', function() {
      it('should call putGroupClass successfully', function(done) {
        //uncomment below and update the code to test putGroupClass
        //instance.putGroupClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerGroupClass', function() {
      it('should call registerGroupClass successfully', function(done) {
        //uncomment below and update the code to test registerGroupClass
        //instance.registerGroupClass(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeTrainer', function() {
      it('should call removeTrainer successfully', function(done) {
        //uncomment below and update the code to test removeTrainer
        //instance.removeTrainer(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
