/**
 * Fitness center backend API
 * backend API for Fitness center
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FitnessCenterBackendApi);
  }
}(this, function(expect, FitnessCenterBackendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FitnessCenterBackendApi.SportTypeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SportTypeApi', function() {
    describe('deleteSportType', function() {
      it('should call deleteSportType successfully', function(done) {
        //uncomment below and update the code to test deleteSportType
        //instance.deleteSportType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSportType', function() {
      it('should call getSportType successfully', function(done) {
        //uncomment below and update the code to test getSportType
        //instance.getSportType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSportTypes', function() {
      it('should call getSportTypes successfully', function(done) {
        //uncomment below and update the code to test getSportTypes
        //instance.getSportTypes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putSportType', function() {
      it('should call putSportType successfully', function(done) {
        //uncomment below and update the code to test putSportType
        //instance.putSportType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerSportType', function() {
      it('should call registerSportType successfully', function(done) {
        //uncomment below and update the code to test registerSportType
        //instance.registerSportType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
